### ISSUE TITLE
Bump major version for ros2 branch

### ISSUE THREAD

**Issue by jspricke** [ros/angles#13]
I would propose to bum the major version for ROS 2 to make it easy to differentiate between both. cf. https://github.com/ros/class_loader/tags for an example.

Would actually be great to remove the 1.12.0 tag then (not sure how much harm it would make, though).

**Comment by tfoote** [comment]
I've chosen not to do that as the API hasn't changed at all so giving a major version bump doesn't make a lot of sense in the semantic versioning type of world. I added enough padding to support one minor version bump between all potential intermittent rosdistros but they haven't been necessary.
