### ISSUE TITLE
Issue with the installation path of the headers

### ISSUE THREAD

**Issue by domire8** [ros/angles#31]
There is an issue with the `CMakeLists.txt` on branch `ros2` since PR #28. Line 23 should be
```
install(DIRECTORY include/ DESTINATION include)
```
instead of
```
install(DIRECTORY include/ DESTINATION include/angles)
```
because the latter results in the `angles.h` header being under `include/angles/angles/angles.h` instead of `include/angles/angles.h`, which breaks the build of a few packages on `galactic` (`joint_trajectory_controller` for instance).

Possibly also related to #30 .

**Comment by domire8** [comment]
Sorry, I did not see #29 . I would highly appreciate a galactic branch though, as suggested [here](https://github.com/ros/angles/pull/28#issuecomment-1013872636]

**Comment by sloretz** [comment]
I created `foxy-devel` and `galactic-devel` branches.

Release repo PR: https://github.com/ros2-gbp/angles-release/pull/1
rosdistro PR: https://github.com/ros/rosdistro/pull/31834

**Comment by sloretz** [comment]
Rolling release now that #32 is merged:

https://github.com/ros/rosdistro/pull/31841
