### ISSUE TITLE
Support for arch?

### ISSUE THREAD

**Issue by Imeguras** [ros/angles#41]
No definition of [angles] for OS [arch], (on galactic)

Is this on the roadmap?

**Comment by DLu** [comment]
Angles is definitely released for galactic, how did you attempt install?

**Comment by Imeguras** [comment]
i meant on arch linux, both through rosdep, and aur it lacks packages
worse is galactic was the only one i managed to install

**Comment by tfoote** [comment]
rosdep resolves not-ROS packages this is a ROS package so you should just put it into your workspace.
